# Generated by Django 4.2.4 on 2023-08-22 22:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('clima', models.CharField(max_length=50)),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 8, 22, 22, 48, 54, 900361, tzinfo=datetime.timezone.utc))),
                ('diameter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gravity', models.IntegerField()),
                ('population', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Personage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('species', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=150)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planet', to='meuApp.planet')),
            ],
        ),
    ]
