# Generated by Django 4.2.4 on 2023-08-22 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuApp', '0002_character_episode_location_delete_personage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 23, 14, 32, 428966, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='episode',
            name='air_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 23, 14, 32, 428966, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='episode',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 23, 14, 32, 428966, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='location',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 23, 14, 32, 428966, tzinfo=datetime.timezone.utc)),
        ),
    ]
