# Generated by Django 4.2.4 on 2023-08-22 23:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meuApp', '0004_alter_character_created_alter_episode_air_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personage', to='meuApp.character'),
        ),
        migrations.AlterField(
            model_name='character',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 23, 34, 28, 739225, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='character',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='meuApp.location'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='air_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 23, 34, 28, 740227, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='episode',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 23, 34, 28, 740227, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='location',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 23, 34, 28, 739225, tzinfo=datetime.timezone.utc)),
        ),
    ]
